<?php


/**
 * Implements hook_form_alter().
 */
function securelogin_form_alter(&$form, &$form_state, $form_id) {
  // securelogin settings
  $securelogin_conf = \Drupal::config('securelogin.settings');
  $securelogin_all_forms = $securelogin_conf->get('all_forms');
  $securelogin_other_forms = $securelogin_conf->get('other_forms');

  if (isset($form_state['build_info']['base_form_id'])) {
    $form_id = $form_state['build_info']['base_form_id'];
  }
  if ($securelogin_all_forms) {
    $form['#https'] = TRUE;
  }
  elseif ($securelogin_conf->get('form_' . $form_id)) {
    $form['#https'] = TRUE;
  }
  elseif ($forms = explode(' ', $securelogin_other_forms)) {
    if (in_array($form_id, $forms)) {
      $form['#https'] = TRUE;
    }
  }
  // Other modules may use #https to indicate that a form should be secured.
  if (!empty($form['#https'])) {
    \Drupal::service('securelogin.API')->securelogin_secure_form($form);
  }
}

/**
 * Implements hook_help().
 */
function securelogin_help($path, $arg) {
  switch($path) {
    case 'admin/help#securelogin':
      return t('Enables passwords to be sent over a secure connection.');
    case 'admin/config/people/securelogin':
      return t('Secure Login allows user login and other forms to be submitted to a configurable secure (HTTPS) URL from the insecure (HTTP) site. By securing the user login forms, a site can enforce secure authenticated sessions, which are immune to <a href="http://en.wikipedia.org/wiki/Session_hijacking">session sidejacking</a>.');
  }
}
